### ISSUE TITLE
Add support for reading secrets from AWS Secrets Manager

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive#280]
# Background
Secrets should not be stored as plaintext in the configuration, nor in files on hdfs or s3. They should be retrieved directly by the Spark job from a vault. Furthermore, secrets' values must not be printed in the logs. As a first vault provider, AWS Secrets Manager should be supported.

# Suggestions

Config (mental model, if we had yaml config)
```
secretsprovider:
  secrets:
    truststorepassword:
     options:
       secretname: <the-secret-name>
       readasmap: true
       key: <the-key>
       encoding: base64
     secretvalue: // should be filled by provider
    otherpassword:
     provider: dummymanager
     options:
       dummykey: <dummy-value>
     secretvalue: // should be filled by provider

  config:
    providers:
      awssecretsmanager:
        class: za.co.absa.hyperdrive.secretsprovider.AwsSecretsManager
      dummymanager:
        class: za.co.absa.hyperdrive.dummymanager
    defaultprovider: awssecretsmanager
reader:
 option:
  kafka:
     ssl.truststore.password: ${secrets.truststorepassword.value}
```

A secret that should be retrieved by aws secrets manager would be configured as follows:

```
secretsprovider.config.providers.awssecretsmanager.class=za.co.absa.hyperdrive.secretsprovider.AwsSecretsManager
secretsprovider.secrets.truststorepassword.provider=awssecretsmanager
secretsprovider.secrets.truststorepassword.options.secretname=<the-secret-name>
secretsprovider.secrets.truststorepassword.options.key=<the-secret-key>
secretsprovider.secrets.truststorepassword.options.encoding=base64
reader.option.kafka.ssl.truststore.password=${secretsprovider.secrets.truststorepassword.secretvalue}
```

In this example, both `awssecretsmanager` and `truststorepassword` are arbitrary identifiers that can be chosen when the configuration is written.

Before the configuration is resolved, all secrets must be resolved by the provider, given the `options` for each secret. Global config for the provider is given by the key-value map under `secrets.config.providers.[provider-id].options`
